// runtime/vue/src/Select.vue
<script setup>
const p = defineProps({ label:String, disabled:Boolean, value:String, placeholder:String, error:String, description:String })
</script>
<template><label class="kumo-label">{{ p.label }}<select class="kumo-control" :disabled="p.disabled" :value="p.value"><option v-if="p.placeholder" disabled>{{ p.placeholder }}</option><option>Apple</option><option>Banana</option><option>Cherry</option></select><span v-if="p.error" class="kumo-error">{{ p.error }}</span><span v-else-if="p.description" class="kumo-description">{{ p.description }}</span></label></template>

// runtime/svelte/src/Select.svelte
<script>
export let label=''; export let disabled=false; export let value=''; export let placeholder=''; export let error=''; export let description='';
</script>
<label class="kumo-label">{label}<select class="kumo-control" {disabled} bind:value>{#if placeholder}<option disabled>{placeholder}</option>{/if}<option>Apple</option><option>Banana</option><option>Cherry</option></select>{#if error}<span class="kumo-error">{error}</span>{:else if description}<span class="kumo-description">{description}</span>{/if}</label>
