// deploy/benchmarks/bakeoff/mitosis/generated/react/Popover.tsx
"use client";
import * as React from "react";
import { useState } from "react";

function Popover(props: any) {
  const [open, setOpen] = useState(() => false);

  return (
    <div>
      <button aria-expanded={open} onClick={(event) => setOpen(!open)}>
        {props.label}
      </button>
      <div hidden={!open}>{props.children}</div>
    </div>
  );
}

export default Popover;

// candidates/mitosis/generated/solid/Popover.tsx
import { createSignal, createMemo } from "solid-js";

function Popover(props: any) {
  const [open, setOpen] = createSignal(false);

  return (
    <>
      <div>
        <button aria-expanded={open()} onClick={(event) => setOpen(!open())}>
          {props.label}
        </button>
        <div hidden={!open()}>{props.children}</div>
      </div>
    </>
  );
}

export default Popover;
