// dx/packages/kumo-solid/package/components/date-picker.tsx
import { splitProps } from "solid-js";
import { Portal } from "solid-js/web";
import type { JSX } from "solid-js";

export interface DatePickerProps extends Record<string, unknown> { children?: JSX.Element; fixture?: unknown; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "5f335d94261bdac9b04be13a3684f1d47504a43360cb208c4a84231a1d259fce";
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
export const semanticVariantDigests = {"single-selected":"90a3e8f4e57496245fa749e6800c37b954ae86c0abed9de8887a1a989de3dbd3"} as const;
const styles: Record<string, string> = {"root":"root","rdp-root":"rdp-root","rdp-month_grid":"rdp-month_grid","rdp-day_button":"rdp-day_button"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
const fixtureText = (value: any): string => value && typeof value === "object" ? String(typeof value.text === "string" ? value.text : "") + (Array.isArray(value.children) ? value.children.map(fixtureText).join("") : "") : "";
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function DatePicker(incoming: DatePickerProps): JSX.Element {
  const props = Object.assign({}, incoming);
  const fixture = props.fixture;
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as DatePickerProps & Record<string, unknown>, []);
  void native; void state; void refs;
  if (Object.prototype.hasOwnProperty.call(props, "aria-label") && semanticEqual(props["aria-label"], "Choose date") && Object.prototype.hasOwnProperty.call(props, "defaultMonthDate") && semanticEqual(props.defaultMonthDate, "2025-01-01") && Object.prototype.hasOwnProperty.call(props, "mode") && semanticEqual(props.mode, "single") && Object.prototype.hasOwnProperty.call(props, "selectedDate") && semanticEqual(props.selectedDate, "2025-01-15")) return (<div aria-label={"Choose date"}><table role={"grid"}></table><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button></div>);
  return (<Portal mount={resolvePortalTarget("document-body")} children={<><div data-kumo-compound={"date-picker"}><div data-kumo-part={"date-picker"}>{(props["date-picker"] as JSX.Element) ?? undefined}</div></div></>} />);
}

export default DatePicker;

// generated/libraries/vue/components/date-picker.vue
<script lang="ts">
export const modelDigest = "5f335d94261bdac9b04be13a3684f1d47504a43360cb208c4a84231a1d259fce"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface DatePickerProps {
  "aria-label"?: string
  "fromDate"?: unknown
  "mode"?: unknown
  "onChange"?: unknown
  "reactDayPickerProps"?: unknown
  "selected"?: unknown
  "toDate"?: unknown
  "defaultMonthDate"?: unknown
  "selectedDate"?: unknown
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<DatePickerProps>(), {})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;ariaLabel&quot;) &amp;&amp; semanticEqual(semanticValues.ariaLabel, &quot;Choose date&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;defaultMonthDate&quot;) &amp;&amp; semanticEqual(semanticValues.defaultMonthDate, &quot;2025-01-01&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;mode&quot;) &amp;&amp; semanticEqual(semanticValues.mode, &quot;single&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;selectedDate&quot;) &amp;&amp; semanticEqual(semanticValues.selectedDate, &quot;2025-01-15&quot;)"><div aria-label="Choose date"><table role="grid"></table><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button></div></template><template v-else><Teleport :to="&quot;document-body&quot;"><div data-kumo-layer="date-picker"><div data-kumo-compound="date-picker" :class="styles.root"><section data-kumo-part="date-picker"><slot name="date-picker"></slot></section></div></div></Teleport></template>
</template>
