// dx/packages/kumo-solid/package/components/grid-item.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface GridItemProps extends Record<string, unknown> { children?: JSX.Element; fixture?: unknown; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "40f49eae26c10cb50f9eff28ca613e0eb9e5cf415f57f0b763ec8e8cc46f2a16";
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
export const semanticVariantDigests = {"default":"51c1d321c43ffacdda6bd6fc684748b42dfba6453c77469911a835a6971f221c","custom-class":"fae0126eee9399750e209d30c90d71037d08b2d983b07c536fe81384697adc57"} as const;
const styles: Record<string, string> = {"root":"root"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
const fixtureText = (value: any): string => value && typeof value === "object" ? String(typeof value.text === "string" ? value.text : "") + (Array.isArray(value.children) ? value.children.map(fixtureText).join("") : "") : "";
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function GridItem(incoming: GridItemProps): JSX.Element {
  const props = Object.assign({}, incoming);
  const fixture = props.fixture;
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as GridItemProps & Record<string, unknown>, []);
  void native; void state; void refs;
  if (Object.prototype.hasOwnProperty.call(props, "children") && semanticEqual(props.children, "Cell") && Object.prototype.hasOwnProperty.call(props, "className") && semanticEqual(props.className, "p-4")) return (<div class="p-4">{props.children}</div>);
  if (Object.prototype.hasOwnProperty.call(props, "children") && semanticEqual(props.children, "Cell")) return (<div>{props.children}</div>);
  return (<div class={mergeStyles(styles.root)}>{props.children}</div>);
}

export default GridItem;

// generated/libraries/vue/components/grid-item.vue
<script lang="ts">
export const modelDigest = "40f49eae26c10cb50f9eff28ca613e0eb9e5cf415f57f0b763ec8e8cc46f2a16"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface GridItemProps {
  "children"?: unknown
  "className"?: string
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<GridItemProps>(), {})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="semanticEqual(renderContent(), &quot;Cell&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;className&quot;) &amp;&amp; semanticEqual(semanticValues.className, &quot;p-4&quot;)"><div class="p-4">{{ renderContent() }}</div></template><template v-else-if="semanticEqual(renderContent(), &quot;Cell&quot;)"><div>{{ renderContent() }}</div></template><template v-else><div :class="[styles[&quot;root&quot;]]"><slot /></div></template>
</template>
