// dx/packages/kumo-solid/package/components/menu-bar.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface MenuBarProps extends Record<string, unknown> { children?: JSX.Element; fixture?: unknown; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "188bad4486283b6daed15b228465d53415f5e138ecb140a8de65b390602a0a22";
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
export const semanticVariantDigests = {"empty-nav-ssr":"5cdeed6857aee33ad3beee01ef718b002e5e7d97daf643c1739e8d71cb4922b0"} as const;
const styles: Record<string, string> = {"root":"root","isolate":"isolate","flex":"flex","rounded-lg":"rounded-lg","ring-kumo-line":"ring-kumo-line","bg-kumo-recessed":"bg-kumo-recessed","shadow-xs":"shadow-xs"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
const fixtureText = (value: any): string => value && typeof value === "object" ? String(typeof value.text === "string" ? value.text : "") + (Array.isArray(value.children) ? value.children.map(fixtureText).join("") : "") : "";
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function MenuBar(incoming: MenuBarProps): JSX.Element {
  const props = Object.assign({"optionIds":false}, incoming);
  const fixture = props.fixture;
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as MenuBarProps & Record<string, unknown>, []);
  void native; void state; void refs;
  if (Object.prototype.hasOwnProperty.call(props, "isActive") && semanticEqual(props.isActive, 0) && Object.prototype.hasOwnProperty.call(props, "options") && semanticEqual(props.options, [])) return (<nav class="isolate flex rounded-lg ring-kumo-line bg-kumo-recessed"></nav>);
  return (<div data-kumo-compound={"menu-bar"}><div data-kumo-part={"root"}>{(props.root as JSX.Element) ?? undefined}</div><div data-kumo-part={"collection"}>{(props.collection as JSX.Element) ?? undefined}</div></div>);
}

export default MenuBar;

// generated/libraries/vue/components/menu-bar.vue
<script lang="ts">
export const modelDigest = "188bad4486283b6daed15b228465d53415f5e138ecb140a8de65b390602a0a22"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface MenuBarProps {
  "className"?: string
  "isActive"?: unknown
  "optionIds"?: boolean
  "options"?: unknown
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<MenuBarProps>(), {"optionIds":false})
const slots = useSlots()
const styles: Record<string,string> = {}
const normalizeSlotContent = (value: any): string => Array.isArray(value) ? value.map(normalizeSlotContent).join('') : value == null || typeof value === 'boolean' ? '' : typeof value === 'string' || typeof value === 'number' ? String(value) : normalizeSlotContent(value.children)
const renderContent = () => props.semanticContent ?? normalizeSlotContent(slots.default?.())
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;isActive&quot;) &amp;&amp; semanticEqual(semanticValues.isActive, 0) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;options&quot;) &amp;&amp; semanticEqual(semanticValues.options, [])"><nav class="isolate flex rounded-lg ring-kumo-line bg-kumo-recessed"></nav></template><template v-else><div data-kumo-compound="menu-bar" :class="styles.root"><section data-kumo-part="root"><slot name="root"></slot></section><section data-kumo-part="collection"><slot name="collection"></slot></section></div></template>
</template>
