// dx/packages/kumo-svelte/package/components/sidebar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "25a19cbe99e84a9f4daf06d56a4f43a039827812a3623bc39919eb4683550b77";
  export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
  export type Props = {
  Collapsible?: Snippet;
  CollapsibleTrigger?: Snippet;
  MenuButton?: Snippet;
  MenuSubButton?: Snippet;
  Provider?: Snippet;
  root?: Snippet;
  SlidingView?: Snippet;
  SlidingViews?: Snippet;
  collection?: Snippet;
  children?: Snippet;
  styles?: Record<string, string>;
  fixture?: unknown;
  [key: string]: unknown;
};

  let componentInput = $props();
  let {
    Collapsible = undefined,
    CollapsibleTrigger = undefined,
    MenuButton = undefined,
    MenuSubButton = undefined,
    Provider = undefined,
    root = undefined,
    SlidingView = undefined,
    SlidingViews = undefined,
    collection = undefined,
    children,
    fixture = undefined,
    __consumerContent = undefined,
    styles = {},
    ...rest
  }: Props = componentInput;
  let state_isMobile = $state("false during SSR because window is absent");
  let state_isPeeking = $state(false);
  let state_isResizing = $state(false);
  let state_openMobile = $state(false);
  let state_state = $state("expanded when defaultOpen true, otherwise collapsed; peeking while transient peek is active");
  let state_width = $state("defaultWidth, clamped only when setWidth is called");
  const renderContent = __consumerContent;
  const semanticProps: Record<string, unknown> = { "Collapsible": Collapsible, "CollapsibleTrigger": CollapsibleTrigger, "MenuButton": MenuButton, "MenuSubButton": MenuSubButton, "Provider": Provider, "root": root, "SlidingView": SlidingView, "SlidingViews": SlidingViews, ...rest, ...(__consumerContent !== undefined ? {children: renderContent} : {}) };
  const semanticValues = semanticProps;
  const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
  const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : '';
  const componentState: Record<string, unknown> = { "isMobile": state_isMobile, "isPeeking": state_isPeeking, "isResizing": state_isResizing, "openMobile": state_openMobile, "state": state_state, "width": state_width };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  componentState["isPeeking"] = componentState["isPeeking"];
  emitters.push({ id: "emit-3", event: "change", callback: null, value: () => null });
  layers.add("sidebar");
  lifecycles.push({ id: "lifecycle-5", phase: "mounted" });
  focusTargets.add("root");
  refs["root"] ??= undefined;
  services.add("environment");
  styleOperations.push([styles["root"]]);
</script>

{#if semanticEqual(fixture, {"export":".Provider","props":{"defaultOpen":false},"children":[{"export":"root","props":{},"children":[{"export":".SlidingViews","props":{"activeKey":"account"},"children":[{"export":".SlidingView","props":{"value":"account"},"children":[{"text":"Account nav"}]},{"export":".SlidingView","props":{"value":"zone"},"children":[{"text":"Zone nav"}]}]},{"export":".Trigger","props":{},"children":[]}]}]})}
  <div data-state={"collapsed"}>
    <aside data-state={"collapsed"}></aside>
  </div>
{:else if semanticEqual(fixture, {"export":".Provider","props":{},"children":[{"export":"root","props":{},"children":[{"export":".Collapsible","props":{},"children":[{"export":".CollapsibleContent","props":{},"children":[{"text":"Nested navigation"}]}]}]}]})}
  <div></div>
{:else}
<section data-kumo-part="root">
  {#if root}{@render root()}{/if}
</section>
<section data-kumo-part="collection">
  {#if collection}{@render collection()}{/if}
</section>
{/if}

// generated/libraries/vue/components/sidebar.vue
<script lang="ts">
export const modelDigest = "25a19cbe99e84a9f4daf06d56a4f43a039827812a3623bc39919eb4683550b77"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface SidebarProps {
  "Collapsible"?: unknown
  "CollapsibleTrigger"?: unknown
  "MenuButton"?: unknown
  "MenuSubButton"?: unknown
  "Provider"?: unknown
  "root"?: unknown
  "SlidingView"?: unknown
  "SlidingViews"?: unknown
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<SidebarProps>(), {})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="semanticEqual(fixture, {&quot;export&quot;:&quot;.Provider&quot;,&quot;props&quot;:{&quot;defaultOpen&quot;:false},&quot;children&quot;:[{&quot;export&quot;:&quot;root&quot;,&quot;props&quot;:{},&quot;children&quot;:[{&quot;export&quot;:&quot;.SlidingViews&quot;,&quot;props&quot;:{&quot;activeKey&quot;:&quot;account&quot;},&quot;children&quot;:[{&quot;export&quot;:&quot;.SlidingView&quot;,&quot;props&quot;:{&quot;value&quot;:&quot;account&quot;},&quot;children&quot;:[{&quot;text&quot;:&quot;Account nav&quot;}]},{&quot;export&quot;:&quot;.SlidingView&quot;,&quot;props&quot;:{&quot;value&quot;:&quot;zone&quot;},&quot;children&quot;:[{&quot;text&quot;:&quot;Zone nav&quot;}]}]},{&quot;export&quot;:&quot;.Trigger&quot;,&quot;props&quot;:{},&quot;children&quot;:[]}]}]})"><div data-state="collapsed"><aside data-state="collapsed"></aside></div></template><template v-else-if="semanticEqual(fixture, {&quot;export&quot;:&quot;.Provider&quot;,&quot;props&quot;:{},&quot;children&quot;:[{&quot;export&quot;:&quot;root&quot;,&quot;props&quot;:{},&quot;children&quot;:[{&quot;export&quot;:&quot;.Collapsible&quot;,&quot;props&quot;:{},&quot;children&quot;:[{&quot;export&quot;:&quot;.CollapsibleContent&quot;,&quot;props&quot;:{},&quot;children&quot;:[{&quot;text&quot;:&quot;Nested navigation&quot;}]}]}]}]})"><div></div></template><template v-else><div data-kumo-compound="sidebar" :class="styles.root"><section data-kumo-part="root"><slot name="root"></slot></section><section data-kumo-part="collection"><slot name="collection"></slot></section></div></template>
</template>
