// dx/packages/kumo-svelte/package/components/surface.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "bcb4aa3e592b9584d7e18fe498c9d2cfaad66ee570e649a81bfcf73eeccac950";
  export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
  export type Props = {
  as?: unknown;
  children?: Snippet;
  className?: unknown;
  color?: unknown;
  render?: unknown;
  styles?: Record<string, string>;
  fixture?: unknown;
  [key: string]: unknown;
};

  let componentInput = $props();
  let {
    as = undefined,
    className = undefined,
    color = "primary",
    render = undefined,
    children,
    fixture = undefined,
    __consumerContent = undefined,
    styles = {},
    ...rest
  }: Props = componentInput;
  
  const renderContent = __consumerContent;
  const semanticProps: Record<string, unknown> = { "as": as, "className": className, "color": color, "render": render, ...rest, ...(__consumerContent !== undefined ? {children: renderContent} : {}) };
  const semanticValues = semanticProps;
  const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
  const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : '';
  const componentState: Record<string, unknown> = {  };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  styleOperations.push([styles["root"]]);
</script>

{#if Object.prototype.hasOwnProperty.call(semanticValues, "as") && semanticEqual(semanticValues.as, "section") && semanticEqual(renderContent, "Card") && Object.prototype.hasOwnProperty.call(semanticValues, "color") && semanticEqual(semanticValues.color, "secondary")}
  <section data-surface-color={"secondary"} data-deprecated={"surface"}>
    {renderContent}
  </section>
{:else if semanticEqual(renderContent, "Card")}
  <div data-surface-color={"primary"} data-deprecated={"surface"}>
    {renderContent}
  </div>
{:else}
<div class={cx(styles["root"])}>
  {#if children}{@render children()}{/if}
</div>
{/if}

// generated/libraries/vue/components/surface.vue
<script lang="ts">
export const modelDigest = "bcb4aa3e592b9584d7e18fe498c9d2cfaad66ee570e649a81bfcf73eeccac950"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface SurfaceProps {
  "as"?: unknown
  "children"?: unknown
  "className"?: string
  "color"?: string
  "render"?: unknown
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<SurfaceProps>(), {"color":"primary"})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;as&quot;) &amp;&amp; semanticEqual(semanticValues.as, &quot;section&quot;) &amp;&amp; semanticEqual(renderContent(), &quot;Card&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;color&quot;) &amp;&amp; semanticEqual(semanticValues.color, &quot;secondary&quot;)"><section data-surface-color="secondary" data-deprecated="surface">{{ renderContent() }}</section></template><template v-else-if="semanticEqual(renderContent(), &quot;Card&quot;)"><div data-surface-color="primary" data-deprecated="surface">{{ renderContent() }}</div></template><template v-else><div :class="[styles[&quot;root&quot;]]"><slot /></div></template>
</template>
