// deploy/benchmarks/bakeoff/mitosis/generated/vue/Popover.vue
<template>
  <div>
    <button :aria-expanded="open" @click="async (event) => (open = !open)">
      {{ label }}
    </button>
    <div :hidden="!open"><slot /></div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "popover",

  props: ["label"],

  data() {
    return { open: false };
  },
});
</script>

// deploy/benchmarks/bakeoff/mitosis/generated/react/Popover.tsx
"use client";
import * as React from "react";
import { useState } from "react";

function Popover(props: any) {
  const [open, setOpen] = useState(() => false);

  return (
    <div>
      <button aria-expanded={open} onClick={(event) => setOpen(!open)}>
        {props.label}
      </button>
      <div hidden={!open}>{props.children}</div>
    </div>
  );
}

export default Popover;
