// candidates/mitosis/generated/svelte/Select.svelte
<script lang="ts">
  export let label;
  export let value;
  export let onChange;
  export let options;
</script>

<label
  >{label}<select
    {value}
    on:change={(event) => {
      onChange(event.target.value);
    }}
  >
    {#each options as option}
      <option value={option}>{option}</option>
    {/each}
  </select></label
>

// deploy/benchmarks/bakeoff/mitosis/generated/react/Select.tsx
"use client";
import * as React from "react";

function Select(props: any) {
  return (
    <label>
      {props.label}
      <select
        value={props.value}
        onChange={(event) => props.onChange(event.target.value)}
      >
        {props.options?.map((option) => (
          <option value={option}>{option}</option>
        ))}
      </select>
    </label>
  );
}

export default Select;
