// candidates/mitosis/generated/svelte/Select.svelte
<script lang="ts">
  export let label;
  export let value;
  export let onChange;
  export let options;
</script>

<label
  >{label}<select
    {value}
    on:change={(event) => {
      onChange(event.target.value);
    }}
  >
    {#each options as option}
      <option value={option}>{option}</option>
    {/each}
  </select></label
>

// deploy/benchmarks/bakeoff/mitosis/generated/solid/Select.tsx
import { For } from "solid-js";

function Select(props: any) {
  return (
    <>
      <label>
        {props.label}
        <select
          value={props.value}
          onChange={(event) => props.onChange(event.target.value)}
        >
          <For each={props.options}>
            {(option, _index) => {
              const index = _index();
              return <option value={option}>{option}</option>;
            }}
          </For>
        </select>
      </label>
    </>
  );
}

export default Select;
