// candidates/mitosis/generated/solid/Dialog.tsx
function Dialog(props: any) {
  return (
    <>
      <div
        role="dialog"
        aria-modal="true"
        aria-label={props.title}
        hidden={!props.open}
      >
        {props.children}
        <button onClick={(event) => props.onClose()}>Close</button>
      </div>
    </>
  );
}

export default Dialog;

// deploy/benchmarks/bakeoff/mitosis/generated/vue/Dialog.vue
<template>
  <div role="dialog" aria-modal="true" :aria-label="title" :hidden="!open">
    <slot /><button @click="async (event) => onClose()">Close</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "dialog",

  props: ["title", "open", "onClose"],
});
</script>
