// candidates/mitosis/generated/svelte/Select.svelte
<script lang="ts">
  export let label;
  export let value;
  export let onChange;
  export let options;
</script>

<label
  >{label}<select
    {value}
    on:change={(event) => {
      onChange(event.target.value);
    }}
  >
    {#each options as option}
      <option value={option}>{option}</option>
    {/each}
  </select></label
>

// deploy/benchmarks/bakeoff/mitosis/generated/vue/Select.vue
<template>
  <label
    >{{ label
    }}<select
      :value="value"
      @change="async (event) => onChange(event.target.value)"
    >
      <template :key="index" v-for="(option, index) in options">
        <option :value="option">{{ option }}</option>
      </template>
    </select></label
  >
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "select",

  props: ["label", "value", "onChange", "options"],
});
</script>
