// deploy/benchmarks/bakeoff/mitosis/generated/svelte/Tabs.svelte
<script lang="ts">
  export let labels;

  let active = 0;
</script>

<div>
  <div role="tablist">
    {#each labels as label, index}
      <button
        role="tab"
        aria-selected={active === index}
        on:click={(event) => {
          active = index;
        }}>{label}</button
      >
    {/each}
  </div>
  <div role="tabpanel">{labels[active]}</div>
</div>

// deploy/benchmarks/bakeoff/mitosis/generated/vue/Tabs.vue
<template>
  <div>
    <div role="tablist">
      <template :key="index" v-for="(label, index) in labels">
        <button
          role="tab"
          :aria-selected="active === index"
          @click="async (event) => (active = index)"
        >
          {{ label }}
        </button>
      </template>
    </div>
    <div role="tabpanel">{{ labels[active] }}</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "tabs",

  props: ["labels"],

  data() {
    return { active: 0 };
  },
});
</script>
