// candidates/mitosis/generated/vue/DatePicker.vue
<template>
  <label
    >{{ label
    }}<input
      type="date"
      :value="value"
      @input="async (event) => onChange(event.target.value)"
  /></label>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "date-picker",

  props: ["label", "value", "onChange"],
});
</script>

// candidates/mitosis/generated/react/DatePicker.tsx
"use client";
import * as React from "react";

function DatePicker(props: any) {
  return (
    <label>
      {props.label}
      <input
        type="date"
        value={props.value}
        onInput={(event) => props.onChange(event.target.value)}
      />
    </label>
  );
}

export default DatePicker;
