// generated/libraries/vue/components/badge.vue
<script lang="ts">
export const modelDigest = "d61594f3236e8d7e4602671f3db5548b0873d563cfc52c9d9249597042a2cf31"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface BadgeProps {
  "appearance"?: unknown
  "children"?: unknown
  "className"?: string
  "variant"?: string
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<BadgeProps>(), {"appearance":"filled","variant":"primary"})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;appearance&quot;) &amp;&amp; semanticEqual(semanticValues.appearance, &quot;dot&quot;) &amp;&amp; semanticEqual(renderContent(), &quot;Healthy&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;variant&quot;) &amp;&amp; semanticEqual(semanticValues.variant, &quot;success&quot;)"><span><span aria-hidden="true" class="bg-kumo-success"></span>{{ renderContent() }}</span></template><template v-else-if="semanticEqual(renderContent(), &quot;PRO&quot;)"><span class="inline-flex bg-kumo-badge-inverted">{{ renderContent() }}</span></template><template v-else><span :class="[styles[&quot;root&quot;]]"><slot /></span></template>
</template>

// dx/packages/kumo-svelte/package/components/badge.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "d61594f3236e8d7e4602671f3db5548b0873d563cfc52c9d9249597042a2cf31";
  export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
  export type Props = {
  appearance?: unknown;
  children: Snippet;
  className?: unknown;
  variant?: unknown;
  styles?: Record<string, string>;
  fixture?: unknown;
  [key: string]: unknown;
};

  let componentInput = $props();
  let {
    appearance = "filled",
    className = undefined,
    variant = "primary",
    children,
    fixture = undefined,
    __consumerContent = undefined,
    styles = {},
    ...rest
  }: Props = componentInput;
  
  const renderContent = __consumerContent;
  const semanticProps: Record<string, unknown> = { "appearance": appearance, "className": className, "variant": variant, ...rest, ...(__consumerContent !== undefined ? {children: renderContent} : {}) };
  const semanticValues = semanticProps;
  const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
  const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : '';
  const componentState: Record<string, unknown> = {  };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  styleOperations.push([styles["root"]]);
</script>

{#if Object.prototype.hasOwnProperty.call(semanticValues, "appearance") && semanticEqual(semanticValues.appearance, "dot") && semanticEqual(renderContent, "Healthy") && Object.prototype.hasOwnProperty.call(semanticValues, "variant") && semanticEqual(semanticValues.variant, "success")}
  <span>
    <span aria-hidden={"true"} class="bg-kumo-success"></span>
    {renderContent}
  </span>
{:else if semanticEqual(renderContent, "PRO")}
  <span class="inline-flex bg-kumo-badge-inverted">
    {renderContent}
  </span>
{:else}
<span class={cx(styles["root"])}>
  {#if children}{@render children()}{/if}
</span>
{/if}
