// dx/packages/kumo-solid/package/components/button.tsx
import { splitProps } from 'solid-js';

export function Button(props) {
  const [local, native] = splitProps(props, ['variant', 'size', 'disabled', 'loading', 'children', 'class']);
  return <button {...native}
    class={['kumo-button', `kumo-button--${local.variant ?? 'primary'}`, `kumo-button--${local.size ?? 'medium'}`, local.class].filter(Boolean).join(' ')}
    disabled={Boolean(local.disabled || local.loading)}
    aria-busy={local.loading ? 'true' : undefined}
  >{local.loading ? 'Loading…' : local.children}</button>;
}

export const modelDigest = "48798c8ab5bf8d756056311749cd7d344b6c82b50134d057656d5f6e4cad48aa";
export default Button;

// dx/packages/kumo-svelte/package/components/button.svelte
<script lang="ts">
  import type { ButtonHTMLAttributes } from 'svelte/elements';

  type Props = ButtonHTMLAttributes & {
    variant?: 'primary' | 'secondary' | 'danger';
    size?: 'small' | 'medium' | 'large';
    loading?: boolean;
  };

  let {
    variant = 'primary',
    size = 'medium',
    loading = false,
    disabled = false,
    type = 'button',
    class: className = '',
    children,
    ...attributes
  }: Props = $props();
</script>

<button
  {...attributes}
  {type}
  class={`kumo-button kumo-button--${variant} kumo-button--${size} ${className}`.trim()}
  disabled={disabled || loading}
  aria-busy={loading || undefined}
>
  {#if loading}Loading…{:else}{@render children?.()}{/if}
</button>
