// generated/libraries/vue/components/command-palette.vue
<script lang="ts">
export const modelDigest = "7e72307448756ba3dce186fdd6d001623e82bf54634bcb1dd046b6ec82f31bf6"
</script>

<script setup lang="ts">
import { onMounted, ref } from 'vue'

interface CommandPaletteProps {
  "compound"?: unknown
  "Dialog"?: unknown
  "Input"?: unknown
  "Panel"?: string
  "Root"?: string
}
const props = withDefaults(defineProps<CommandPaletteProps>(), {})
const emit = defineEmits(["update:open","change"])
const styles: Record<string,string> = {"root":"kumo-command-palette-root"}
const modal = ref(true)
const root = ref<HTMLElement | null>(null)
onMounted(() => { void props })
</script>

<template>
  <div data-kumo-compound="command-palette" :class="styles.root"><section data-kumo-part="root"><slot name="root"></slot></section><section data-kumo-part="collection"><slot name="collection"></slot></section></div>
</template>

// dx/packages/kumo-svelte/package/components/command-palette.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "7e72307448756ba3dce186fdd6d001623e82bf54634bcb1dd046b6ec82f31bf6";
  export type Props = {
  compound?: Snippet;
  Dialog?: Snippet;
  Input?: Snippet;
  Panel?: Snippet;
  Root?: Snippet;
  collection?: Snippet;
  root?: Snippet;
  children?: Snippet;
  styles?: Record<string, string>;
  [key: string]: unknown;
};

  let {
    compound = undefined,
    Dialog = undefined,
    Input = undefined,
    Panel = undefined,
    Root = undefined,
    collection = undefined,
    root = undefined,
    children,
    styles = {},
    ...rest
  }: Props = $props();
  let state_highlight = $state("first result auto-highlighted always and kept as results change");
  let state_modal = $state(true);
  let state_open = $state("required controlled boolean");
  let state_query = $state("controlled value or empty");
  const props: Record<string, unknown> = { "compound": compound, "Dialog": Dialog, "Input": Input, "Panel": Panel, "Root": Root };
  const state: Record<string, unknown> = { "highlight": state_highlight, "modal": state_modal, "open": state_open, "query": state_query };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  state["modal"] = state["modal"];
  emitters.push({ id: "emit-3", event: "change", callback: null, value: () => null });
  focusTargets.add("root");
  layers.add("command-palette");
  lifecycles.push({ id: "lifecycle-6", phase: "mounted" });
  refs["root"] ??= undefined;
  styleOperations.push([styles["root"]]);
</script>

<section data-kumo-part="root">
  {#if root}{@render root()}{/if}
</section>
<section data-kumo-part="collection">
  {#if collection}{@render collection()}{/if}
</section>
