// generated/libraries/vue/components/dialog.vue
<script lang="ts">
export const modelDigest = "f9517f6c346751f7fb38e9984e7e08637053542c11e623d7b71778e55bf138cb"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface DialogProps {
  "Close"?: unknown
  "Description"?: unknown
  "Dialog"?: unknown
  "Root"?: string
  "Title"?: unknown
  "Trigger"?: unknown
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<DialogProps>(), {})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template ><Teleport :to="&quot;document-body&quot;"><div data-kumo-layer="dialog"><div data-kumo-compound="dialog" :class="styles.root"><section data-kumo-part="dialog"><slot name="dialog"></slot></section></div></div></Teleport></template>
</template>

// dx/packages/kumo-svelte/package/components/dialog.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "f9517f6c346751f7fb38e9984e7e08637053542c11e623d7b71778e55bf138cb";
  export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
  export type Props = {
  Close?: Snippet;
  Description?: Snippet;
  Dialog?: Snippet;
  Root?: Snippet;
  Title?: Snippet;
  Trigger?: Snippet;
  dialog?: Snippet;
  children?: Snippet;
  styles?: Record<string, string>;
  fixture?: unknown;
  [key: string]: unknown;
};

  let componentInput = $props();
  let {
    Close = undefined,
    Description = undefined,
    Dialog = undefined,
    Root = undefined,
    Title = undefined,
    Trigger = undefined,
    dialog = undefined,
    children,
    fixture = undefined,
    __consumerContent = undefined,
    styles = {},
    ...rest
  }: Props = componentInput;
  let state_open = $state("Base UI controlled/defaultOpen; default closed");
  let state_role = $state("dialog");
  let state_size = $state("base");
  const renderContent = __consumerContent;
  const semanticProps: Record<string, unknown> = { "Close": Close, "Description": Description, "Dialog": Dialog, "Root": Root, "Title": Title, "Trigger": Trigger, ...rest, ...(__consumerContent !== undefined ? {children: renderContent} : {}) };
  const semanticValues = semanticProps;
  const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
  const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : '';
  const componentState: Record<string, unknown> = { "open": state_open, "role": state_role, "size": state_size };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  componentState["role"] = componentState["role"];
  emitters.push({ id: "emit-3", event: "change", callback: null, value: () => null });
  layers.add("dialog");
  lifecycles.push({ id: "lifecycle-5", phase: "mounted" });
  focusTargets.add("root");
  refs["root"] ??= undefined;
  styleOperations.push([styles["root"]]);
</script>

{#if browser}
  <div data-kumo-portal-target={"document-body"} data-kumo-layer="dialog">
    <section data-kumo-part="dialog">
      {#if dialog}{@render dialog()}{/if}
    </section>
  </div>
{/if}
