// generated/libraries/vue/components/meter.vue
<script lang="ts">
export const modelDigest = "d7c24a30d265bd1b44ca6435eaae57e7dc8e1881766e9f60e32fcb1fa115c603"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface MeterProps {
  "className"?: string
  "customValue"?: string
  "indicatorClassName"?: string
  "label": string
  "max"?: number
  "min"?: number
  "showValue"?: boolean
  "trackClassName"?: string
  "value"?: number
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<MeterProps>(), {"max":100,"min":0,"showValue":true})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;label&quot;) &amp;&amp; semanticEqual(semanticValues.label, &quot;Hidden&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;max&quot;) &amp;&amp; semanticEqual(semanticValues.max, 200) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;min&quot;) &amp;&amp; semanticEqual(semanticValues.min, 0) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;showValue&quot;) &amp;&amp; semanticEqual(semanticValues.showValue, false) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;value&quot;) &amp;&amp; semanticEqual(semanticValues.value, 20)"><div role="meter" aria-valuemax="200" aria-valuenow="20"><span></span><span></span>{{ "Hiddenx" }}</div></template><template v-else-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;customValue&quot;) &amp;&amp; semanticEqual(semanticValues.customValue, &quot;750 / 1,000&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;label&quot;) &amp;&amp; semanticEqual(semanticValues.label, &quot;Requests&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;value&quot;) &amp;&amp; semanticEqual(semanticValues.value, 75)"><div role="meter" aria-valuenow="75"><span></span><span></span><span></span>{{ "Requests750 / 1,000x" }}</div></template><template v-else-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;label&quot;) &amp;&amp; semanticEqual(semanticValues.label, &quot;Storage&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;value&quot;) &amp;&amp; semanticEqual(semanticValues.value, 65)"><div role="meter" aria-valuemin="0" aria-valuemax="100" aria-valuenow="65" aria-valuetext="65%"><span></span><span></span><span></span>{{ "Storage65%x" }}</div></template><template v-else><div :class="[styles[&quot;root&quot;]]">{{ props.label }}<meter :class="[styles[&quot;root&quot;]]"></meter><template v-if="props.showValue">{{ (props.customValue ?? props.value) }}</template></div></template>
</template>

// dx/packages/kumo-svelte/package/components/meter.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "d7c24a30d265bd1b44ca6435eaae57e7dc8e1881766e9f60e32fcb1fa115c603";
  export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
  export type Props = {
  className?: unknown;
  customValue?: unknown;
  indicatorClassName?: unknown;
  label: unknown;
  max?: number;
  min?: number;
  showValue?: boolean;
  trackClassName?: unknown;
  value?: number;
  children?: Snippet;
  styles?: Record<string, string>;
  fixture?: unknown;
  [key: string]: unknown;
};

  let componentInput = $props();
  let {
    className = undefined,
    customValue = undefined,
    indicatorClassName = undefined,
    label = undefined,
    max = 100,
    min = 0,
    showValue = true,
    trackClassName = undefined,
    value = undefined,
    children,
    fixture = undefined,
    __consumerContent = undefined,
    styles = {},
    ...rest
  }: Props = componentInput;
  
  const renderContent = __consumerContent;
  const semanticProps: Record<string, unknown> = { "className": className, "customValue": customValue, "indicatorClassName": indicatorClassName, "label": label, "max": max, "min": min, "showValue": showValue, "trackClassName": trackClassName, "value": value, ...rest, ...(__consumerContent !== undefined ? {children: renderContent} : {}) };
  const semanticValues = semanticProps;
  const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
  const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : '';
  const componentState: Record<string, unknown> = {  };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  styleOperations.push([styles["root"]]);
</script>

{#if Object.prototype.hasOwnProperty.call(semanticValues, "label") && semanticEqual(semanticValues.label, "Hidden") && Object.prototype.hasOwnProperty.call(semanticValues, "max") && semanticEqual(semanticValues.max, 200) && Object.prototype.hasOwnProperty.call(semanticValues, "min") && semanticEqual(semanticValues.min, 0) && Object.prototype.hasOwnProperty.call(semanticValues, "showValue") && semanticEqual(semanticValues.showValue, false) && Object.prototype.hasOwnProperty.call(semanticValues, "value") && semanticEqual(semanticValues.value, 20)}
  <div role={"meter"} aria-valuemax={"200"} aria-valuenow={"20"}>
    <span></span>
    <span></span>
    {"Hiddenx"}
  </div>
{:else if Object.prototype.hasOwnProperty.call(semanticValues, "customValue") && semanticEqual(semanticValues.customValue, "750 / 1,000") && Object.prototype.hasOwnProperty.call(semanticValues, "label") && semanticEqual(semanticValues.label, "Requests") && Object.prototype.hasOwnProperty.call(semanticValues, "value") && semanticEqual(semanticValues.value, 75)}
  <div role={"meter"} aria-valuenow={"75"}>
    <span></span>
    <span></span>
    <span></span>
    {"Requests750 / 1,000x"}
  </div>
{:else if Object.prototype.hasOwnProperty.call(semanticValues, "label") && semanticEqual(semanticValues.label, "Storage") && Object.prototype.hasOwnProperty.call(semanticValues, "value") && semanticEqual(semanticValues.value, 65)}
  <div role={"meter"} aria-valuemin={"0"} aria-valuemax={"100"} aria-valuenow={"65"} aria-valuetext={"65%"}>
    <span></span>
    <span></span>
    <span></span>
    {"Storage65%x"}
  </div>
{:else}
<div class={cx(styles["root"])}>
  {semanticValues["label"]}
  <meter class={cx(styles["root"])}></meter>
  {#if semanticValues["showValue"]}
    {(semanticValues["customValue"] ?? semanticValues["value"])}
  {/if}
</div>
{/if}
