// generated/libraries/solid/popover.tsx
import { splitProps } from "solid-js";
import { Portal } from "solid-js/web";
import type { JSX } from "solid-js";

export interface PopoverProps extends Record<string, unknown> { children?: JSX.Element; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "ad3f10680d31c621c1bc54e0a910834f60fbc9d5776de398d94abac24dc0d45d";
const styles: Record<string, string> = {"root":"root","data-kumo-component=Popover":"data-kumo-component=Popover","data-kumo-part=trigger":"data-kumo-part=trigger","data-starting-style":"data-starting-style","data-ending-style":"data-ending-style","origin-[var(--transform-origin)]":"origin-[var(--transform-origin)]"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function Popover(incoming: PopoverProps): JSX.Element {
  const props = Object.assign({}, incoming);
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as PopoverProps & Record<string, unknown>, []);
  void native; void state; void refs;
  return (<Portal mount={resolvePortalTarget("document-body")} children={<><div data-kumo-compound={"popover"}><div data-kumo-part={"popover"}>{(props.popover as JSX.Element) ?? undefined}</div></div></>} />);
}

export function PopoverClose(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Close">{local.children}</div>;
}

export function PopoverContent(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Content">{local.children}</div>;
}

export function PopoverDescription(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Description">{local.children}</div>;
}

export function PopoverTitle(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Title">{local.children}</div>;
}

export function PopoverTrigger(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Trigger">{local.children}</div>;
}

Object.defineProperty(Popover, "Close", {value:PopoverClose, enumerable:true});
Object.defineProperty(Popover, "Content", {value:PopoverContent, enumerable:true});
Object.defineProperty(Popover, "Description", {value:PopoverDescription, enumerable:true});
Object.defineProperty(Popover, "Title", {value:PopoverTitle, enumerable:true});
Object.defineProperty(Popover, "Trigger", {value:PopoverTrigger, enumerable:true});

export default Popover;

// dx/packages/kumo-svelte/package/components/popover.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "ad3f10680d31c621c1bc54e0a910834f60fbc9d5776de398d94abac24dc0d45d";
  export type Props = {
  Close?: Snippet;
  Content?: Snippet;
  Root?: Snippet;
  "Title/Description"?: Snippet;
  Trigger?: Snippet;
  popover?: Snippet;
  children?: Snippet;
  styles?: Record<string, string>;
  [key: string]: unknown;
};

  let {
    Close = undefined,
    Content = undefined,
    Root = undefined,
    Title_Description = undefined,
    Trigger = undefined,
    popover = undefined,
    children,
    styles = {},
    ...rest
  }: Props = $props();
  let state_anchor = $state("trigger unless explicit element/ref/virtual element/resolver");
  let state_focus = $state("trigger remains focusable");
  let state_open = $state("defaultOpen or controlled open; otherwise false");
  const props: Record<string, unknown> = { "Close": Close, "Content": Content, "Root": Root, "Title/Description": Title_Description, "Trigger": Trigger };
  const state: Record<string, unknown> = { "anchor": state_anchor, "focus": state_focus, "open": state_open };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  state["focus"] = state["focus"];
  emitters.push({ id: "emit-3", event: "change", callback: null, value: () => null });
  layers.add("popover");
  lifecycles.push({ id: "lifecycle-5", phase: "mounted" });
  services.add("environment");
  styleOperations.push([styles["root"]]);
</script>

{#if browser}
  <div data-kumo-portal-target={"document-body"} data-kumo-layer="popover">
    <section data-kumo-part="popover">
      {#if popover}{@render popover()}{/if}
    </section>
  </div>
{/if}
