// generated/libraries/solid/text.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface TextProps extends Record<string, unknown> { children?: JSX.Element; styles?: Record<string, string>; }
export const modelDigest = "60219ad3fa185b8a9db3e82cc4fc77b1b0683b2881bcf6b0460646bb320e67c2";
const styles: Record<string, string> = {"root":"root","text-kumo-default":"text-kumo-default","text-base":"text-base"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function Text(incoming: TextProps): JSX.Element {
  const props = Object.assign({"bold":false,"size":"base","truncate":false,"variant":"body"}, incoming);
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as TextProps & Record<string, unknown>, []);
  void native; void state; void refs;
  return (<span class={mergeStyles(styles.root)}>{props.children}</span>);
}

export default Text;

// dx/packages/kumo-svelte/package/components/text.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "60219ad3fa185b8a9db3e82cc4fc77b1b0683b2881bcf6b0460646bb320e67c2";
  export type Props = {
  as?: unknown;
  bold?: boolean;
  children?: Snippet;
  DANGEROUS_className?: Snippet;
  DANGEROUS_style?: Snippet;
  size?: unknown;
  truncate?: boolean;
  variant?: unknown;
  styles?: Record<string, string>;
  [key: string]: unknown;
};

  let {
    as = undefined,
    bold = false,
    DANGEROUS_className = undefined,
    DANGEROUS_style = undefined,
    size = "base",
    truncate = false,
    variant = "body",
    children,
    styles = {},
    ...rest
  }: Props = $props();
  
  const props: Record<string, unknown> = { "as": as, "bold": bold, "children": children, "DANGEROUS_className": DANGEROUS_className, "DANGEROUS_style": DANGEROUS_style, "size": size, "truncate": truncate, "variant": variant };
  const state: Record<string, unknown> = {  };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  styleOperations.push([styles["root"]]);
</script>

<span class={cx(styles["root"])}>
  {#if children}{@render children()}{/if}
</span>
