// deploy/benchmarks/bakeoff/mitosis/generated/solid/Tabs.tsx
import { For, createSignal, createMemo } from "solid-js";

function Tabs(props: any) {
  const [active, setActive] = createSignal(0);

  return (
    <>
      <div>
        <div role="tablist">
          <For each={props.labels}>
            {(label, _index) => {
              const index = _index();
              return (
                <button
                  role="tab"
                  aria-selected={active() === index}
                  onClick={(event) => setActive(index)}
                >
                  {label}
                </button>
              );
            }}
          </For>
        </div>
        <div role="tabpanel">{props.labels[active()]}</div>
      </div>
    </>
  );
}

export default Tabs;

// deploy/benchmarks/bakeoff/mitosis/generated/svelte/Tabs.svelte
<script lang="ts">
  export let labels;

  let active = 0;
</script>

<div>
  <div role="tablist">
    {#each labels as label, index}
      <button
        role="tab"
        aria-selected={active === index}
        on:click={(event) => {
          active = index;
        }}>{label}</button
      >
    {/each}
  </div>
  <div role="tabpanel">{labels[active]}</div>
</div>
