// candidates/mitosis/generated/react/Tabs.tsx
"use client";
import * as React from "react";
import { useState } from "react";

function Tabs(props: any) {
  const [active, setActive] = useState(() => 0);

  return (
    <div>
      <div role="tablist">
        {props.labels?.map((label, index) => (
          <button
            role="tab"
            aria-selected={active === index}
            onClick={(event) => setActive(index)}
          >
            {label}
          </button>
        ))}
      </div>
      <div role="tabpanel">{props.labels[active]}</div>
    </div>
  );
}

export default Tabs;

// deploy/benchmarks/bakeoff/mitosis/generated/svelte/Tabs.svelte
<script lang="ts">
  export let labels;

  let active = 0;
</script>

<div>
  <div role="tablist">
    {#each labels as label, index}
      <button
        role="tab"
        aria-selected={active === index}
        on:click={(event) => {
          active = index;
        }}>{label}</button
      >
    {/each}
  </div>
  <div role="tabpanel">{labels[active]}</div>
</div>
