// dx/packages/kumo-solid/package/components/dropdown-menu.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface DropdownMenuProps extends Record<string, unknown> { children?: JSX.Element; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "4af0c8a7d7b8b60e856eaff59dc37b9cf13972ebeb4a5efd3e6776a353898221";
const styles: Record<string, string> = {"root":"root","data-highlighted":"data-highlighted","data-disabled":"data-disabled","data-popup-open":"data-popup-open","data-starting-style":"data-starting-style","data-ending-style":"data-ending-style","text-kumo-danger":"text-kumo-danger"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function DropdownMenu(incoming: DropdownMenuProps): JSX.Element {
  const props = Object.assign({}, incoming);
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as DropdownMenuProps & Record<string, unknown>, []);
  void native; void state; void refs;
  return (<div data-kumo-compound={"dropdown-menu"}><div data-kumo-part={"root"}>{(props.root as JSX.Element) ?? undefined}</div><div data-kumo-part={"collection"}>{(props.collection as JSX.Element) ?? undefined}</div></div>);
}

export function DropdownMenuContent(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Content">{local.children}</div>;
}

export function DropdownMenuItem(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Item">{local.children}</div>;
}

export function DropdownMenuSub(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Sub">{local.children}</div>;
}

export function DropdownMenuSubContent(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="SubContent">{local.children}</div>;
}

export function DropdownMenuSubTrigger(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="SubTrigger">{local.children}</div>;
}

export function DropdownMenuTrigger(props: CompoundPartProps): JSX.Element {
  const [local, native] = splitProps(props, ["children"]);
  return <div {...native} data-kumo-part="Trigger">{local.children}</div>;
}

Object.defineProperty(DropdownMenu, "Content", {value:DropdownMenuContent, enumerable:true});
Object.defineProperty(DropdownMenu, "Item", {value:DropdownMenuItem, enumerable:true});
Object.defineProperty(DropdownMenu, "Sub", {value:DropdownMenuSub, enumerable:true});
Object.defineProperty(DropdownMenu, "SubContent", {value:DropdownMenuSubContent, enumerable:true});
Object.defineProperty(DropdownMenu, "SubTrigger", {value:DropdownMenuSubTrigger, enumerable:true});
Object.defineProperty(DropdownMenu, "Trigger", {value:DropdownMenuTrigger, enumerable:true});

export default DropdownMenu;

// generated/libraries/svelte/components/dropdown-menu.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "4af0c8a7d7b8b60e856eaff59dc37b9cf13972ebeb4a5efd3e6776a353898221";
  export type Props = {
  CheckboxItem?: Snippet;
  "Content/SubContent"?: Snippet;
  Item?: Snippet;
  "Label/Separator/Shortcut/Group"?: Snippet;
  LinkItem?: Snippet;
  "RadioGroup/RadioItem/RadioItemIndicator"?: Snippet;
  Root?: Snippet;
  "Sub/SubTrigger"?: Snippet;
  Trigger?: Snippet;
  collection?: Snippet;
  root?: Snippet;
  children?: Snippet;
  styles?: Record<string, string>;
  [key: string]: unknown;
};

  let {
    CheckboxItem = undefined,
    Content_SubContent = undefined,
    Item = undefined,
    Label_Separator_Shortcut_Group = undefined,
    LinkItem = undefined,
    RadioGroup_RadioItem_RadioItemIndicator = undefined,
    Root = undefined,
    Sub_SubTrigger = undefined,
    Trigger = undefined,
    collection = undefined,
    root = undefined,
    children,
    styles = {},
    ...rest
  }: Props = $props();
  let state_checkboxAndRadioValue = $state("from item/group props");
  let state_highlightedItem = $state(null);
  let state_open = $state("controlled/uncontrolled Base UI root state");
  let state_submenuOpen = $state("controlled/uncontrolled Base UI state");
  const props: Record<string, unknown> = { "CheckboxItem": CheckboxItem, "Content/SubContent": Content_SubContent, "Item": Item, "Label/Separator/Shortcut/Group": Label_Separator_Shortcut_Group, "LinkItem": LinkItem, "RadioGroup/RadioItem/RadioItemIndicator": RadioGroup_RadioItem_RadioItemIndicator, "Root": Root, "Sub/SubTrigger": Sub_SubTrigger, "Trigger": Trigger };
  const state: Record<string, unknown> = { "checkboxAndRadioValue": state_checkboxAndRadioValue, "highlightedItem": state_highlightedItem, "open": state_open, "submenuOpen": state_submenuOpen };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  state["highlightedItem"] = state["highlightedItem"];
  emitters.push({ id: "emit-3", event: "change", callback: null, value: () => null });
  focusTargets.add("root");
  refs["root"] ??= undefined;
  layers.add("dropdown-menu");
  lifecycles.push({ id: "lifecycle-7", phase: "mounted" });
  styleOperations.push([styles["root"]]);
</script>

<section data-kumo-part="root">
  {#if root}{@render root()}{/if}
</section>
<section data-kumo-part="collection">
  {#if collection}{@render collection()}{/if}
</section>
