// dx/packages/kumo-solid/package/components/link.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface LinkProps extends Record<string, unknown> { children?: JSX.Element; fixture?: unknown; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "66e89c0778455462b2e0f570cd8e93d03c70b2080ad1568935860a9da97e5065";
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
export const semanticVariantDigests = {"internal":"29e7ed1c47e2e5846d73164683b615e304a7c4b479fa40d162ff644a54fe0a42","plain-external":"55849ea241349409983a1f64b0567fc60bcfddac212cbfbd2a2b0d73ca8bd710"} as const;
const styles: Record<string, string> = {"root":"root","group/link":"group/link","inline-flex":"inline-flex","items-center":"items-center"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
const normalizeRenderContent = (value: unknown, accessors = false): string => {
  if (value == null || value === false || value === true) return "";
  if (typeof value === "string" || typeof value === "number") return String(value);
  if (Array.isArray(value)) return value.map(item => normalizeRenderContent(item, accessors)).join("");
  if (accessors && typeof value === "function") return normalizeRenderContent(value(), accessors);
  if (typeof value === "object") { const item = value as {text?: unknown; children?: unknown}; return (typeof item.text === "string" ? item.text : "") + (Array.isArray(item.children) ? item.children.map(child => normalizeRenderContent(child)).join("") : ""); }
  return "";
};
const normalizeFixture = (value: unknown): unknown => Array.isArray(value) ? value.map(normalizeFixture) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, item]) => [key, normalizeFixture(item)])) : value;
const fixtureText = (value: unknown): string => normalizeRenderContent(value);
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function Link(incoming: LinkProps): JSX.Element {
  const props = Object.assign({"variant":"inline"}, incoming);
  const fixture = props.fixture;
  const renderContent = normalizeRenderContent(props.children, true);
  const normalizedFixture = normalizeFixture(fixture);
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as LinkProps & Record<string, unknown>, []);
  void native; void state; void refs;
  if (semanticEqual(renderContent, "External") && Object.prototype.hasOwnProperty.call(props, "href") && semanticEqual(props.href, "https://example.com") && Object.prototype.hasOwnProperty.call(props, "variant") && semanticEqual(props.variant, "plain")) return (<a href={"https://example.com"} class="hover:text-kumo-link/70">{props.children}</a>);
  if (semanticEqual(renderContent, "Docs") && Object.prototype.hasOwnProperty.call(props, "href") && semanticEqual(props.href, "/docs")) return (<a href={"/docs"} data-kumo-component={"Link"} class="text-kumo-link underline">{props.children}</a>);
  return (<a href={(props.href as any)} class={mergeStyles(styles.root)}>{props.children}</a>);
}

export default Link;

// generated/libraries/svelte/components/link.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "66e89c0778455462b2e0f570cd8e93d03c70b2080ad1568935860a9da97e5065";
  export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
  export type Props = {
  children?: Snippet;
  className?: unknown;
  href?: unknown;
  render?: unknown;
  variant?: unknown;
  styles?: Record<string, string>;
  fixture?: unknown;
  [key: string]: unknown;
};

  let componentInput = $props();
  let {
    className = undefined,
    href = undefined,
    render = undefined,
    variant = "inline",
    children,
    fixture = undefined,
    __consumerContent = undefined,
    styles = {},
    ...rest
  }: Props = componentInput;
  
  const renderContent = __consumerContent;
  const semanticProps: Record<string, unknown> = { "className": className, "href": href, "render": render, "variant": variant, ...rest, ...(__consumerContent !== undefined ? {children: renderContent} : {}) };
  const semanticValues = semanticProps;
  const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
  const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : '';
  const componentState: Record<string, unknown> = {  };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  styleOperations.push([styles["root"]]);
</script>

{#if semanticEqual(renderContent, "External") && Object.prototype.hasOwnProperty.call(semanticValues, "href") && semanticEqual(semanticValues.href, "https://example.com") && Object.prototype.hasOwnProperty.call(semanticValues, "variant") && semanticEqual(semanticValues.variant, "plain")}
  <a href={"https://example.com"} class="hover:text-kumo-link/70">
    {renderContent}
  </a>
{:else if semanticEqual(renderContent, "Docs") && Object.prototype.hasOwnProperty.call(semanticValues, "href") && semanticEqual(semanticValues.href, "/docs")}
  <a href={"/docs"} data-kumo-component={"Link"} class="text-kumo-link underline">
    {renderContent}
  </a>
{:else}
<a href={semanticValues["href"]} class={cx(styles["root"])}>
  {#if children}{@render children()}{/if}
</a>
{/if}
