// generated/libraries/svelte/components/code.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "abe340a97570aaf2d55b46c6015819101f40daa70452db116f62bad2a5ff7ced";
  export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
  export type Props = {
  className?: unknown;
  code: unknown;
  lang?: unknown;
  style?: unknown;
  values?: unknown;
  children?: Snippet;
  styles?: Record<string, string>;
  [key: string]: unknown;
};

  let {
    className = undefined,
    code = undefined,
    lang = "ts",
    style = undefined,
    values = undefined,
    children,
    styles = {},
    ...rest
  }: Props = $props();
  
  const props: Record<string, unknown> = { "className": className, "code": code, "lang": lang, "style": style, "values": values };
  const state: Record<string, unknown> = {  };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  void "render-1";
  styleOperations.push([styles["root"]]);
</script>

<code class={cx(styles["root"])}>
  {props["code"]}
</code>

// dx/packages/kumo-solid/package/components/code.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface CodeProps extends Record<string, unknown> { children?: JSX.Element; styles?: Record<string, string>; }
export const modelDigest = "5e7c1a6e6d7b7973979fc806a00d8999299a443db7eda7b9234417bc397a0fba";
const styles: Record<string, string> = {"root":"root","font-mono":"font-mono","text-sm":"text-sm","text-kumo-subtle":"text-kumo-subtle"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function Code(incoming: CodeProps): JSX.Element {
  const props = Object.assign({"lang":"ts"}, incoming);
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as CodeProps & Record<string, unknown>, []);
  void native; void state; void refs;
  return (<code class={mergeStyles(styles.root)}>{(props.code as any)}</code>);
}

export default Code;
