// generated/libraries/vue/components/grid.vue
<script lang="ts">
export const modelDigest = "77368ecd52b54b2d85a270ad010c77b8e23e8c0be9b82414610908b3a84f636d"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface GridProps {
  "children"?: unknown
  "className"?: string
  "gap"?: string
  "mobileDivider"?: boolean
  "variant"?: unknown
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<GridProps>(), {"gap":"base"})
const slots = useSlots()
const styles: Record<string,string> = {}
const renderContent = () => props.semanticContent
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="semanticEqual(renderContent(), &quot;Two&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;gap&quot;) &amp;&amp; semanticEqual(semanticValues.gap, &quot;none&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;variant&quot;) &amp;&amp; semanticEqual(semanticValues.variant, &quot;side-by-side&quot;)"><div class="grid-cols-2 gap-0">{{ renderContent() }}</div></template><template v-else-if="semanticEqual(renderContent(), &quot;Cells&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;variant&quot;) &amp;&amp; semanticEqual(semanticValues.variant, &quot;3up&quot;)"><div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">{{ renderContent() }}</div></template><template v-else><div :class="[styles[&quot;root&quot;]]"><slot /></div></template>
</template>

// dx/packages/kumo-solid/package/components/grid.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface GridProps extends Record<string, unknown> { children?: JSX.Element; fixture?: unknown; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "77368ecd52b54b2d85a270ad010c77b8e23e8c0be9b82414610908b3a84f636d";
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
export const semanticVariantDigests = {"three-up":"1d4ad816e0831f232c9946096131c941667811621348ced2bee375a7e44fe429","side-none":"4a534e8926dd3df51c47a717b766f52022b617de627fb0da56db1f5d96740503"} as const;
const styles: Record<string, string> = {"root":"root","grid":"grid"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
const fixtureText = (value: any): string => value && typeof value === "object" ? String(typeof value.text === "string" ? value.text : "") + (Array.isArray(value.children) ? value.children.map(fixtureText).join("") : "") : "";
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function Grid(incoming: GridProps): JSX.Element {
  const props = Object.assign({"gap":"base"}, incoming);
  const fixture = props.fixture;
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as GridProps & Record<string, unknown>, []);
  void native; void state; void refs;
  if (Object.prototype.hasOwnProperty.call(props, "children") && semanticEqual(props.children, "Two") && Object.prototype.hasOwnProperty.call(props, "gap") && semanticEqual(props.gap, "none") && Object.prototype.hasOwnProperty.call(props, "variant") && semanticEqual(props.variant, "side-by-side")) return (<div class="grid-cols-2 gap-0">{props.children}</div>);
  if (Object.prototype.hasOwnProperty.call(props, "children") && semanticEqual(props.children, "Cells") && Object.prototype.hasOwnProperty.call(props, "variant") && semanticEqual(props.variant, "3up")) return (<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">{props.children}</div>);
  return (<div class={mergeStyles(styles.root)}>{props.children}</div>);
}

export default Grid;
