// dx/packages/kumo-svelte/package/components/switch.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
   const browser = typeof document !== 'undefined';

  export const modelDigest = "ed2dc968d94168f193e43c4ace0c4c5a0eef92e88c8bbe1a3e168bf1f2b424b9";
  export type Props = {
  checked?: boolean;
  disabled?: boolean;
  group?: unknown;
  label?: unknown;
  onCheckedChange?: unknown;
  size?: unknown;
  onCheckedChange?: (value: unknown) => void;
  children?: Snippet;
  styles?: Record<string, string>;
  [key: string]: unknown;
};

  let {
    checked = false,
    disabled = false,
    group = undefined,
    label = undefined,
    onCheckedChange = undefined,
    size = "base",
    children,
    styles = {},
    ...rest
  }: Props = $props();
  let state_controlled = $state("checked");
  let state_uncontrolled = $state("absence of checked");
  const props: Record<string, unknown> = { "checked": checked, "disabled": disabled, "group": group, "label": label, "onCheckedChange": onCheckedChange, "size": size };
  const state: Record<string, unknown> = { "controlled": state_controlled, "uncontrolled": state_uncontrolled };
  const refs: Record<string, HTMLElement | undefined> = {};
  const emitters: Array<{id:string,event:string,callback:string|null,value:()=>unknown}> = [];
  const focusTargets = new Set<string>();
  const lifecycles: Array<{id:string,phase:string}> = [];
  const services = new Set<string>();
  const layers = new Set<string>();
  const styleOperations: unknown[][] = [];
  const cx = (...values: unknown[]) => values.filter(Boolean).join(' ');
  state["controlled"] = state["controlled"];
  emitters.push({ id: "emit-2", event: "change", callback: null, value: () => null });
  void "render-3";
  styleOperations.push([styles["root"]]);
</script>

<button class={cx(styles["root"])}></button>

// dx/packages/kumo-solid/package/components/switch.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface SwitchProps extends Record<string, unknown> { children?: JSX.Element; styles?: Record<string, string>; }
export const modelDigest = "ed2dc968d94168f193e43c4ace0c4c5a0eef92e88c8bbe1a3e168bf1f2b424b9";
const styles: Record<string, string> = {"root":"root","h-4 w-8":"h-4 w-8","h-4.5 w-9":"h-4.5 w-9","h-5 w-10":"h-5 w-10"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function Switch(incoming: SwitchProps): JSX.Element {
  const props = Object.assign({"checked":false,"disabled":false,"size":"base"}, incoming);
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as SwitchProps & Record<string, unknown>, []);
  void native; void state; void refs;
  return (<button class={mergeStyles(styles.root)}></button>);
}

export default Switch;
