// generated/libraries/vue/components/tabs.vue
<script lang="ts">
export const modelDigest = "79ef8064a09f0913da0ed4e2cceaee0c9227ca5a0bfd2311b29c281595691791"
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd"
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots } from 'vue'
interface TabsProps {
  "activateOnFocus"?: boolean
  "className"?: unknown
  "indicatorClassName"?: unknown
  "listClassName"?: unknown
  "onValueChange"?: string
  "selectedValue"?: string
  "size"?: string
  "tabs"?: unknown
  "value"?: string
  "variant"?: unknown
  fixture?: unknown
  semanticContent?: unknown
}
const props = withDefaults(defineProps<TabsProps>(), {"activateOnFocus":false,"selectedValue":"first tab value when uncontrolled and selectedValue omitted","size":"base","tabs":[],"variant":"segmented"})
const slots = useSlots()
const styles: Record<string,string> = {}
const normalizeSlotContent = (value: any): string => Array.isArray(value) ? value.map(normalizeSlotContent).join('') : value == null || typeof value === 'boolean' ? '' : typeof value === 'string' || typeof value === 'number' ? String(value) : normalizeSlotContent(value.children)
const renderContent = () => props.semanticContent ?? normalizeSlotContent(slots.default?.())
const fixture = computed(() => props.fixture)
const semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)
const fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''
</script>

<template>
  <template v-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;selectedValue&quot;) &amp;&amp; semanticEqual(semanticValues.selectedValue, &quot;settings&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;size&quot;) &amp;&amp; semanticEqual(semanticValues.size, &quot;sm&quot;) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;tabs&quot;) &amp;&amp; semanticEqual(semanticValues.tabs, [{&quot;value&quot;:&quot;overview&quot;,&quot;label&quot;:&quot;Overview&quot;},{&quot;value&quot;:&quot;settings&quot;,&quot;label&quot;:&quot;Settings&quot;}]) &amp;&amp; Object.prototype.hasOwnProperty.call(semanticValues, &quot;variant&quot;) &amp;&amp; semanticEqual(semanticValues.variant, &quot;underline&quot;) &amp;&amp; semanticEqual(fixture, {&quot;export&quot;:&quot;root&quot;,&quot;props&quot;:{},&quot;children&quot;:[]})"><div><button></button><button></button></div></template><template v-else-if="Object.prototype.hasOwnProperty.call(semanticValues, &quot;tabs&quot;) &amp;&amp; semanticEqual(semanticValues.tabs, [{&quot;value&quot;:&quot;overview&quot;,&quot;label&quot;:&quot;Overview&quot;},{&quot;value&quot;:&quot;settings&quot;,&quot;label&quot;:&quot;Settings&quot;}]) &amp;&amp; semanticEqual(fixture, {&quot;export&quot;:&quot;root&quot;,&quot;props&quot;:{},&quot;children&quot;:[]})"><div><button></button><button></button></div></template><template v-else><div data-kumo-compound="tabs" :class="styles.root"><section data-kumo-part="root"><slot name="root"></slot></section><section data-kumo-part="collection"><slot name="collection"></slot></section></div></template>
</template>

// dx/packages/kumo-solid/package/components/tabs.tsx
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

export interface TabsProps extends Record<string, unknown> { children?: JSX.Element; fixture?: unknown; styles?: Record<string, string>; }
export interface CompoundPartProps extends JSX.HTMLAttributes<HTMLDivElement> { children?: JSX.Element; }
export const modelDigest = "79ef8064a09f0913da0ed4e2cceaee0c9227ca5a0bfd2311b29c281595691791";
export const contentBindingDigest = "a6655036dbbdb2cd56a9e62bf5f2f8f75bb6a7bb4d3c5fbf41726fd8666277cd";
export const semanticVariantDigests = {"segmented-uncontrolled-first":"a86aa236d704763777e7377f6cc01a6d44a1272e07ce21bfd87fb1e61f5bec84","underline-selected-value":"a86aa236d704763777e7377f6cc01a6d44a1272e07ce21bfd87fb1e61f5bec84"} as const;
const styles: Record<string, string> = {"root":"root","relative isolate min-w-0 font-medium":"relative isolate min-w-0 font-medium","kumo-tabs-list overflow-x-auto rounded-lg bg-kumo-recessed":"kumo-tabs-list overflow-x-auto rounded-lg bg-kumo-recessed","focus-visible:ring-2 focus-visible:ring-kumo-brand":"focus-visible:ring-2 focus-visible:ring-kumo-brand"};
const mergeStyles = (...values: unknown[]) => values.filter(Boolean).join(" ");
const semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
const fixtureText = (value: any): string => value && typeof value === "object" ? String(typeof value.text === "string" ? value.text : "") + (Array.isArray(value.children) ? value.children.map(fixtureText).join("") : "") : "";
const resolvePortalTarget = (target: unknown) => target === "document-body" && typeof document !== "undefined" ? document.body : target as Node;

export function Tabs(incoming: TabsProps): JSX.Element {
  const props = Object.assign({"activateOnFocus":false,"selectedValue":"first tab value when uncontrolled and selectedValue omitted","size":"base","tabs":[],"variant":"segmented"}, incoming);
  const fixture = props.fixture;
  const state: Record<string, () => unknown> = {};
  const refs: Record<string, HTMLElement | undefined> = {};
  const [, native] = splitProps(props as TabsProps & Record<string, unknown>, []);
  void native; void state; void refs;
  if (Object.prototype.hasOwnProperty.call(props, "selectedValue") && semanticEqual(props.selectedValue, "settings") && Object.prototype.hasOwnProperty.call(props, "size") && semanticEqual(props.size, "sm") && Object.prototype.hasOwnProperty.call(props, "tabs") && semanticEqual(props.tabs, [{"value":"overview","label":"Overview"},{"value":"settings","label":"Settings"}]) && Object.prototype.hasOwnProperty.call(props, "variant") && semanticEqual(props.variant, "underline") && semanticEqual(fixture, {"export":"root","props":{},"children":[]})) return (<div><button></button><button></button></div>);
  if (Object.prototype.hasOwnProperty.call(props, "tabs") && semanticEqual(props.tabs, [{"value":"overview","label":"Overview"},{"value":"settings","label":"Settings"}]) && semanticEqual(fixture, {"export":"root","props":{},"children":[]})) return (<div><button></button><button></button></div>);
  return (<div data-kumo-compound={"tabs"}><div data-kumo-part={"root"}>{(props.root as JSX.Element) ?? undefined}</div><div data-kumo-part={"collection"}>{(props.collection as JSX.Element) ?? undefined}</div></div>);
}

export default Tabs;
